### ISSUE TITLE
[FEAT]: Directly train multimodal model for IRFL data split

### ISSUE THREAD

**Issue by Jasonqi146** [lwaekfjlk/mmodel-soup#70]
### Description

The current pipeline of collecting zero-shot predictions on IRFL is not effective as the labels may be difficult to understand in zero-shot manner. To be consistent with the Sarcasm data, we want to use the same multimodal model, ALBEF, to train first and split according to predictions.

**Comment by lwaekfjlk** [comment]
fixed
